version: '3.8'

# Portainer Stack for Photography CMS
# Deploy this via Portainer Web UI -> Stacks -> Add Stack -> Web Editor
# Make sure to set the environment variables in Portainer's environment variables section

services:
  mongodb:
    image: mongo:7
    container_name: photography-cms-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: photography-cms
    volumes:
      - photography-mongodb-data:/data/db
    networks:
      - photography-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5
    labels:
      - "com.photography.service=database"

  cms:
    build:
      context: .
      dockerfile: Dockerfile
    image: photography-cms:latest
    container_name: photography-cms
    restart: unless-stopped
    ports:
      - "${CMS_PORT:-3000}:3000"
    environment:
      MONGODB_URI: mongodb://mongodb:27017/photography-cms
      DATABASE_URI: mongodb://mongodb:27017/photography-cms
      PAYLOAD_SECRET: ${PAYLOAD_SECRET}
      PAYLOAD_PUBLIC_SERVER_URL: ${PAYLOAD_PUBLIC_SERVER_URL}
      PORT: 3000
      NODE_ENV: production
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - photography-network
    volumes:
      - photography-media:/app/media
    labels:
      - "com.photography.service=cms"
      - "traefik.enable=true"
      - "traefik.http.routers.photography-cms.rule=Host(`cms.yourdomain.com`)"
      - "traefik.http.services.photography-cms.loadbalancer.server.port=3000"

volumes:
  photography-mongodb-data:
    driver: local
  photography-media:
    driver: local

networks:
  photography-network:
    driver: bridge
